from __future__ import annotations

import io
import json
import os
import re
import zipfile
from pathlib import Path
from typing import Annotated

from fastapi import FastAPI, Form, Request
from fastapi.responses import HTMLResponse, Response
from fastapi.templating import Jinja2Templates

ACCESS_PASSWORD = os.environ.get("ACCESS_PASSWORD") or None
GITHUB_REPO = os.environ.get(
    "GITHUB_REPO", "thomascortebeeck-kidsnovel/ticketswap"
)
GIT_BRANCH = os.environ.get("GIT_BRANCH", "main")

app = FastAPI(title="TicketSwap helper - Setup")
_TEMPLATES_DIR = Path(__file__).parent / "templates"
templates = Jinja2Templates(directory=str(_TEMPLATES_DIR))


@app.get("/healthz")
def healthz() -> dict:
    return {"ok": True}


@app.get("/", response_class=HTMLResponse)
def index(request: Request) -> HTMLResponse:
    return templates.TemplateResponse(
        request,
        "index.html",
        {
            "error": None,
            "access_password_required": ACCESS_PASSWORD is not None,
            "github_repo": GITHUB_REPO,
            "git_branch": GIT_BRANCH,
            "form": {},
        },
    )


# --- validation helpers ---

_PHONE_RE = re.compile(r"^\d{10,15}$")
_APIKEY_RE = re.compile(r"^\d{4,12}$")
_TS_URL_RE = re.compile(r"^https://(?:www\.)?ticketswap\.com/[^\s]+", re.IGNORECASE)
_VALID_MODES = ("auto", "fcfs", "raffle")


def _normalize_phone(s: str) -> str:
    return re.sub(r"\D+", "", s or "")


def _validate(form: dict) -> tuple[dict, list[str]]:
    """Returns (cleaned, errors)."""
    errors: list[str] = []
    cleaned: dict = {}

    phone = _normalize_phone(form.get("whatsapp_phone", ""))
    if not _PHONE_RE.fullmatch(phone):
        errors.append(
            "WhatsApp number must be 10-15 digits with country code "
            "(e.g. +32472123456)."
        )
    cleaned["whatsapp_phone"] = phone

    apikey = (form.get("whatsapp_apikey") or "").strip()
    if not _APIKEY_RE.fullmatch(apikey):
        errors.append("CallMeBot APIKEY must be 4-12 digits.")
    cleaned["whatsapp_apikey"] = apikey

    cleaned["email_enabled"] = bool(form.get("email_enabled"))
    if cleaned["email_enabled"]:
        smtp_user = (form.get("smtp_user") or "").strip()
        smtp_pass = (form.get("smtp_pass") or "").strip()
        alert_to = (form.get("alert_to") or smtp_user).strip()
        if not (smtp_user and smtp_pass and alert_to):
            errors.append(
                "Email is enabled but Gmail address, App Password, "
                "or recipient is missing."
            )
        cleaned["smtp_host"] = (form.get("smtp_host") or "smtp.gmail.com").strip()
        try:
            cleaned["smtp_port"] = int(form.get("smtp_port") or 587)
        except ValueError:
            cleaned["smtp_port"] = 587
        cleaned["smtp_user"] = smtp_user
        cleaned["smtp_pass"] = smtp_pass
        cleaned["alert_to"] = alert_to
        cleaned["imap_enabled"] = bool(form.get("imap_enabled"))

    event_url = (form.get("event_url") or "").strip()
    if not _TS_URL_RE.match(event_url):
        errors.append("Event URL must be a https://www.ticketswap.com/... URL.")
    cleaned["event_url"] = event_url

    label = (form.get("event_label") or "").strip()
    if not label:
        errors.append("Label is required (e.g. 'Rosalia Antwerp').")
    cleaned["event_label"] = label

    raw_max = (form.get("event_max_price") or "").strip()
    if raw_max:
        try:
            cleaned["event_max_price"] = float(raw_max)
            if cleaned["event_max_price"] <= 0:
                errors.append("Max price must be positive (or leave it empty).")
        except ValueError:
            errors.append(f"Max price '{raw_max}' is not a number.")
    else:
        cleaned["event_max_price"] = None

    raw_qty = (form.get("event_quantity") or "").strip()
    if raw_qty:
        try:
            qty = int(raw_qty)
            if qty <= 0:
                errors.append("Quantity must be at least 1.")
            cleaned["event_quantity"] = qty
        except ValueError:
            errors.append(f"Quantity '{raw_qty}' is not a whole number.")
    else:
        cleaned["event_quantity"] = None

    mode = (form.get("event_mode") or "auto").strip().lower()
    if mode not in _VALID_MODES:
        errors.append(f"Mode must be one of {_VALID_MODES}.")
    cleaned["event_mode"] = mode

    try:
        poll = int(form.get("event_poll") or 60)
    except ValueError:
        poll = -1
    if poll < 30:
        errors.append("Polling interval must be at least 30 seconds.")
    cleaned["event_poll"] = poll

    return cleaned, errors


def _build_env(c: dict) -> str:
    lines = [
        "# Generated by the TicketSwap helper setup wizard.",
        "# Don't share this file - it contains your CallMeBot apikey.",
        "",
        f"WHATSAPP_PHONE={c['whatsapp_phone']}",
        f"WHATSAPP_APIKEY={c['whatsapp_apikey']}",
    ]
    if c.get("email_enabled"):
        lines += [
            "",
            f"SMTP_HOST={c['smtp_host']}",
            f"SMTP_PORT={c['smtp_port']}",
            f"SMTP_USER={c['smtp_user']}",
            f"SMTP_PASS={c['smtp_pass']}",
            f"ALERT_TO={c['alert_to']}",
        ]
        if c.get("imap_enabled"):
            lines += [
                "IMAP_HOST=imap.gmail.com",
                f"IMAP_USER={c['smtp_user']}",
                f"IMAP_PASS={c['smtp_pass']}",
            ]
    lines += [
        "",
        "TICKETSWAP_PROFILE_DIR=./.chromium-profile",
        "WATCHES_PATH=./watches.json",
        "",
    ]
    return "\n".join(lines)


def _build_watches(c: dict) -> str:
    return json.dumps(
        [
            {
                "label": c["event_label"],
                "url": c["event_url"],
                "max_price_eur": c["event_max_price"],
                "quantity": c["event_quantity"],
                "mode": c["event_mode"],
                "active": True,
                "polling_seconds": c["event_poll"],
                "cooldown_seconds": 600,
            }
        ],
        indent=2,
    ) + "\n"


def _build_install_txt() -> str:
    return f"""TicketSwap helper - install instructions
==========================================

This zip contains:
  .env           your secret config (WhatsApp + email, do not share)
  watches.json   the events you want to watch

Step 1. Install Python 3.11 or newer
   https://www.python.org/downloads/
   On Windows, tick "Add python.exe to PATH" during install.

Step 2. Open a terminal
   Mac:     Cmd+Space, type "Terminal", press Enter
   Windows: Win key,    type "PowerShell", press Enter

Step 3. Download the bot
   git clone https://github.com/{GITHUB_REPO}.git
   cd ticketswap

Step 4. Copy the files from this zip
   Drop .env and watches.json into the "ticketswap" folder you just
   downloaded. Replace any existing files of the same name.

Step 5. Install dependencies
   Mac / Linux:
     python3 -m venv .venv
     source .venv/bin/activate
     pip install -e .
     playwright install chromium

   Windows (PowerShell):
     python -m venv .venv
     .venv\\Scripts\\Activate.ps1
     pip install -e .
     playwright install chromium

Step 6. Confirm WhatsApp + email work
   python -m ticketswap test-alerts

Step 7. Log in to TicketSwap once
   python -m ticketswap login

Step 8. Start watching
   python -m ticketswap run

Leave the terminal open. When a ticket appears, your phone gets a
WhatsApp message with the cart URL. Tap it, the TicketSwap app opens,
pay within ~10 minutes.

Full README: https://github.com/{GITHUB_REPO}/blob/{GIT_BRANCH}/README.md
"""


def _build_zip(cleaned: dict) -> bytes:
    buf = io.BytesIO()
    with zipfile.ZipFile(buf, "w", zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("ticketswap-config/.env", _build_env(cleaned))
        zf.writestr("ticketswap-config/watches.json", _build_watches(cleaned))
        zf.writestr("ticketswap-config/INSTALL.txt", _build_install_txt())
    return buf.getvalue()


@app.post("/generate")
def generate(
    request: Request,
    whatsapp_phone: Annotated[str, Form()],
    whatsapp_apikey: Annotated[str, Form()],
    event_url: Annotated[str, Form()],
    event_label: Annotated[str, Form()],
    event_mode: Annotated[str, Form()] = "auto",
    event_poll: Annotated[int, Form()] = 60,
    event_max_price: Annotated[str, Form()] = "",
    event_quantity: Annotated[str, Form()] = "",
    email_enabled: Annotated[str, Form()] = "",
    smtp_host: Annotated[str, Form()] = "",
    smtp_port: Annotated[int, Form()] = 587,
    smtp_user: Annotated[str, Form()] = "",
    smtp_pass: Annotated[str, Form()] = "",
    alert_to: Annotated[str, Form()] = "",
    imap_enabled: Annotated[str, Form()] = "",
    access_password: Annotated[str, Form()] = "",
) -> Response:
    form = {
        "whatsapp_phone": whatsapp_phone,
        "whatsapp_apikey": whatsapp_apikey,
        "event_url": event_url,
        "event_label": event_label,
        "event_mode": event_mode,
        "event_poll": event_poll,
        "event_max_price": event_max_price,
        "event_quantity": event_quantity,
        "email_enabled": email_enabled,
        "smtp_host": smtp_host,
        "smtp_port": smtp_port,
        "smtp_user": smtp_user,
        "smtp_pass": smtp_pass,
        "alert_to": alert_to,
        "imap_enabled": imap_enabled,
    }

    if ACCESS_PASSWORD and access_password != ACCESS_PASSWORD:
        return templates.TemplateResponse(
            request,
            "index.html",
            {
                "error": "Wrong access password.",
                "access_password_required": True,
                "github_repo": GITHUB_REPO,
                "git_branch": GIT_BRANCH,
                "form": form,
            },
            status_code=401,
        )

    cleaned, errors = _validate(form)
    if errors:
        return templates.TemplateResponse(
            request,
            "index.html",
            {
                "error": " ".join(errors),
                "access_password_required": ACCESS_PASSWORD is not None,
                "github_repo": GITHUB_REPO,
                "git_branch": GIT_BRANCH,
                "form": form,
            },
            status_code=400,
        )

    zip_bytes = _build_zip(cleaned)
    return Response(
        content=zip_bytes,
        media_type="application/zip",
        headers={
            "Content-Disposition": 'attachment; filename="ticketswap-config.zip"',
            "Cache-Control": "no-store",
        },
    )
